name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'



jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.17'

    - name: Install Dependencies
      run: go mod tidy

    - name: Run Unit Tests
      run: go test ./backend/...

    - name: Performance Testing
      run: |
        # Placeholder for performance testing scripts
        echo "Running performance tests..."

    - name: Security Checks
      run: |
        go get github.com/securego/gosec/cmd/gosec
        gosec ./backend/...

    - name: Build Docker image
      run: docker build -t myapp-backend:${{ github.sha }} ./backend

    - name: Log in to Docker Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Registry
      run: docker push myapp-backend:${{ github.sha }}

